version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: deepcenter-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - deepcenter

  nginx:
    image: nginx:alpine
    container_name: deepcenter-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - deepcenter

  db:
    image: mysql:8.0
    container_name: deepcenter-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: deepcenter
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: secret
      MYSQL_USER: deepcenter
    volumes:
      - dbdata:/var/lib/mysql/
    ports:
      - "3306:3306"
    networks:
      - deepcenter

networks:
  deepcenter:
    driver: bridge

volumes:
  dbdata:
    driver: local
